# Generated by Django 2.2.19 on 2021-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
